name: IslandCraft
version: 1.0.9_mc-1.13-support
description: Changes the biome distribution of the world to create an ocean with islands
authors: [hoqhuuep, Jatti]
website: http://dev.bukkit.org/bukkit-plugins/islandcraft/
main: com.github.hoqhuuep.islandcraft.bukkit.IslandCraftPlugin
load: STARTUP
commands:
    ic:
      description: IslandCraft commands
      aliases: [island,islandcraft]